### ISSUE TITLE
CodeGenUtil.validateModel no longer working in Papyrus

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#137]
We have an Eclipse plugin that wraps your CodeGenUtil class for a "bulk validate/generate" menu option that displays a checkable list of all the models in the workspace for which to validate. We call into the CodeGenUtil's methods (validateModels, generateIDL, generateDescriptors). The generate methods are working as expected but the validateModels is not. The method always returns success. When I invalidate a model like BasicPubSub and confirm it is invalid with your CX right click "CX Validation" option, the [CodeGenUtil.validateModel method ](https://github.com/ZeligsoftDev/CX4CBDDS/blob/e5805a05e875a6fbe4aa165e049bcaa56b86a4c6/bundles/com.zeligsoft.domain.dds4ccm.codegen/src/com/zeligsoft/domain/dds4ccm/codegen/utils/CodeGenUtil.java#L163) still returns an OK status.

In addition, RSA used to write a "Validation: 0 error(s) 0 warning(s)" message to the Eclipse console when validation succeeded. Papyrus only writes errors to the Model Validation View, not successes so it's difficult to tell when model validations have indeed succeeded as nothing is shown to the user. It would be nice to also have some sort of validation success message for each model that is validated through the right click "CX Validation" option as well as through the CodeGenUtil class.

**Comment by ysroh** [comment]
Never mind. You mentioned already that you are listing models from the workspace. I am looking to see if I can do the validation without opening the model editor.

**Comment by J17359** [comment]
We list all physical .uml files from the workspace. The user chooses which models they wish to validate and then our plugin loops through those selected models and calls `CX.validateModel(selectedModel)`.

**Comment by ysroh** [comment]
In order to make this work in Papyrus, each model that requires validation needs to be opened in a Papyrus model editor as the validation framework is tightly coupled with the service provided by each Model editor. The generation however does not require this because all we need is the UML model.

I will try to make changes to see if there is already a model editor open for the URI resource provided if not I will force to open the model editor and run validation.

This is one of the things that become more complicated in Papyrus compared to RSA using a single project explorer to show models. :(

**Comment by ysroh** [comment]
Would it be sufficient to return the status of whether the model is valid or not? not generating error logs in the model validation view? If we do not need to generate UI markers then we don't need to open the model editor.  Users need to open the invalid model to run the validation again to generate model validation markers in the view.

**Comment by J17359** [comment]
Hmmm, I would much rather prefer that our tool mimics the CX Validation right click menu option you all provide. We have a lot of users that generally want to validate many models in their workspace at once without having to go and right click on every individual model. If we could get the error output AND successful validation output thrown to the Model Validation view, that would be nice.

But a workaround for having the CX.validateModel method just return the status would probably be ok for now. We'd likely still want the longer term solution to mimic the CX Validation right click menu option, though.

**Comment by ysroh** [comment]
I agree that it would be more useful that way. It is unfortunate that the model validation view is attached to the individual Papyrus editor. In order to report to the validation view, a Papyrus editor for each model needs to be open prior to run model validation. Even if you validate all models in the workspace once you will need to click on the individual Model editor to see the model validation view attached to each model editor. There is no one for all model validation view in Papyrus.

What I will do is that I can fix this without involving the model validation view for now but I will create a new enhancement feature to deal with this next depending on the priorities.

**Comment by ysroh** [comment]
I have merged the suggested fix to the papyrus branch and created a new issue for reporting validation results to the model validation view. The CX validation now writes validation results message to the console.

**Comment by J17359** [comment]
Tested this out this morning. I am now getting a Null Pointer Exception (NPE) when calling the validateModel() method from CodeGenUtil. It's throw from https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/bundles/com.zeligsoft.domain.dds4ccm.codegen/src/com/zeligsoft/domain/dds4ccm/codegen/utils/CodeGenUtil.java#L177 which is calling https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/bundles/com.zeligsoft.base.ui/src/com/zeligsoft/base/ui/utils/BaseUIUtil.java#L633. It looks like line 177 in the CodeGenUtil class was changed in your attempted fix so maybe that introduced something? All I did was tell our wrapper to call CodeGenUtil.validateModel() as we did in the past and the NPE was throw immediately. The model was open in the Papyrus perspective when this all happened.

I am running off the latest source on GitHub (hash 8ae9960490a4d816d29b9e2ae54a339e098cc7b7).

**Comment by ysroh** [comment]
Looks like null is returned for getting an active workbench window which is not usual.
I will try to see if I can reproduce this.

**Comment by ysroh** [comment]
I can't reproduce the NPE issue on my end. Can you please let me know a bit more details about your workbench state when validation is called? anything that might be unusual?
Do you get this NPE all the time? I never had an issue getting the active workbench window before so I need to figure out how to reproduce the issue first.

**Comment by ysroh** [comment]
I reproduced the problem. Thanks

**Comment by ysroh** [comment]
You must be running your wrapper on a separate non-ui thread. Can you try to use org.eclipse.ui.progress.UIJob instead of Job? The validation should be run on UI thread now in order to open model editor and report validation results.

**Comment by ysroh** [comment]
I committed a fix for this so you don't have to change your code. The validation code is now running in UI thread.

**Comment by J17359** [comment]
> 
> 
> I committed a fix for this so you don't have to change your code. The validation code is now running in UI thread.

Awesome! Thanks @ysroh. I will test on my end now.

**Comment by ysroh** [comment]
I realized that there could be a race condition between threads. I committed the fix for this.

**Comment by J17359** [comment]
@ysroh - I finally had time to test your latest code (results below):

**Zeligsoft "CX Validation" right-click menu option:**
* Successful validation is now written to the "Console" view - 🙂 
* I cannot get this option to catch **invalid** models any longer - ☹️ 

**CodeGenUtils.validateModel() invocation:**
* Still does not push any model validation printouts to either the "Model Validation" view or the "Console" view, regardless if I already had the model open in the "Model Explorer" view or not. No results shown for either pass or fail - ☹️

**Comment by ysroh** [comment]
Thanks for the feedback.
I had to put our own traversal strategy due to an issue in Papyrus. However, I found out that only the first strategy is kept for model validation while trying to reproduce your issue on my end.  This problem only occurs with the installed version, not from my dev environment.  I've been trying to make our strategy register first but wasn't successful. I will try to revert codegen util changes and see if I can consistently produce a working version.

**Comment by ysroh** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=564601
I reported a bug against EMF validation service.

**Comment by ysroh** [comment]
Can you please try the latest build to see if the validation issue is fixed?

**Comment by J17359** [comment]
> Can you please try the latest build to see if the validation issue is fixed?

@ysroh Zeligsoft "CX Validation" right-click menu option:
* Successful validation when model is valid - 🙂
* Invalid models caught correctly - 🙂

CodeGenUtils.validateModel() invocation:
* Still does not push any model validation printouts to either the "Model Validation" view or the "Console" view, regardless if I already had the model open in the "Model Explorer" view or not. No results shown for either valid or invalid models - ☹️

So it seems like we're back where we started.

**Comment by ysroh** [comment]
So the workaround for emf validation traversal strategy works fine but I am not sure why codegen.util validation does not report to the validation view. I think it would be helpful how you are calling the validation from your wrapper class. I need some more info to reproduce on my end. Thanks

**Comment by J17359** [comment]
@ysroh  - Here is a snippet of what we're doing. As you can see, we're just calling the CX.validateModel() method, looping over each model the user selected from the workspace. All my testing on this GitHub issue has been with a single model so far though...

         
    // Reference to the Zeligsoft CX utilities object
    private static final CodeGenUtil CX = CodeGenUtil.INSTANCE;

    private Collection<IFile> models;

    /**
    * This method performs the actual work of validating. No user interaction may be done in this method.
    * 
    * @param monitor progress monitor
    * @return completion status
    */
    public IStatus performTask(IProgressMonitor monitor)
    {
        if (models == null || models.isEmpty())
        {
            progressDone(monitor);
            return OK_STATUS;
        }

        String taskName = Messages.TaginfoChecker_6;

        SubMonitor progress = SubMonitor.convert(monitor, taskName, models.size());
        try
        {
            List<IStatus> statuses = new ArrayList<IStatus>();

            // Validate the selected models
            for (IFile model : models)
            {
                if (progress.isCanceled())
                {
                    return CANCEL_STATUS;
                }

                progress.subTask(Messages.TaginfoChecker_10 + model.getName());

                IStatus returnedStatus = CX.validateModel(GenerateUtils.convertToURI(model));

                if (returnedStatus.getSeverity() >= IStatus.WARNING)
                {
                    IStatus status = new Status(IStatus.ERROR, PLUGIN_ID, "Failed to validate model for: " + model.getName(), returnedStatus.getException());
                    statuses.add(status);
                }

                progress.worked(1);
            }

            if (statuses.size() != 0)
            {
                IStatus[] statusArray = new IStatus[statuses.size()];
                StringBuilder message = new StringBuilder();
                for (int i = 0; i < statuses.size(); i++)
                {
                    IStatus stat = statuses.get(i);
                    message.append(stat.getMessage()).append("\n");
                    statusArray[i] = stat;
                }

                IStatus thrownStatus = new MultiStatus(PLUGIN_ID, IStatus.ERROR, statusArray, message.toString(),
                statuses.get(0).getException());
                throw new CoreException(thrownStatus);
            }
        }
        catch (CoreException e)
        {
            logAndOpenStatus(e.getStatus());
            return e.getStatus();
        }
        finally
        {
            progressDone(progress, monitor);
        }

        return OK_STATUS;
    }

**Comment by ysroh** [comment]
Thanks I will try to reproduce it on my environment.

**Comment by ysroh** [comment]
I still cannot reproduce this issue on my installed version.
Can you explain what happens when you run your code to validate the model? 
    - Do you get console output saying that the model is validated?
    - Does the Papyrus editor open up for the input model when it is not open in the editor page? If the model is already open then the editor should be focused
    - Do you see any error logs?
    - Can you explain how you make performTask(...) call? I know that you are running it on a non-ui thread so I am curious if that made any difference.

**Comment by J17359** [comment]
> 
> 
> I still cannot reproduce this issue on my installed version.
> Can you explain what happens when you run your code to validate the model?
> - Do you get console output saying that the model is validated?

There is absolutely nothing that happens, no output to the "console" or "model validation" views  in Eclipse

> - Does the Papyrus editor open up for the input model when it is not open in the editor page? If the model is already open then the editor should be focused

I've so far tested while the model was already open in the Papyrus editor. A quick test this morning shows that when the model is not opened, nothing happens - model NOT opened in editor or model explorer.

> - Do you see any error logs?

Good call! I hadn't checked that view yet. Yes, I get an "unhandled event loop exception" coming from the org.eclipse.ui plugin. See attached.
[CodeGenUtils_Error.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/4830637/CodeGenUtils_Error.txt)

> - Can you explain how you make performTask(...) call? I know that you are running it on a non-ui thread so I am curious if that made any difference.

So the original code from my previous comment is the "ValidateChecker" class. Below is the "ValidateJob" class that calls into the ValidateChecker class's performTask method:

    import java.util.List;

    import org.eclipse.core.resources.IProject;
    import org.eclipse.core.resources.WorkspaceJob;
    import org.eclipse.core.runtime.CoreException;
    import org.eclipse.core.runtime.IProgressMonitor;
    import org.eclipse.core.runtime.IStatus;
    import org.eclipse.core.runtime.NullProgressMonitor;

    public class ValidateJob extends WorkspaceJob
    {
       // List of source projects
       private final List<IProject> allProjects;

       public ValidateJob(List<IProject> projects)
       {
          super("Validate Models");

          allProjects = projects;

          setUser(true);
          setPriority(BUILD);
       }

       /*
        * (non-Javadoc)
        * @see org.eclipse.core.resources.WorkspaceJob#runInWorkspace(org.eclipse.core.runtime.IProgressMonitor)
        */
       @Override
       public IStatus runInWorkspace(IProgressMonitor monitor) throws CoreException
       {
          // Initialize Progress Monitor
          if (monitor == null)
          {
             monitor = new NullProgressMonitor();
          }

          // Create object and initialize it to validate the models
          ValidateChecker check = new ValidateChecker();
          IStatus validateStatus = check.validateModels(allProjects, monitor);
          if (validateStatus.getSeverity() == IStatus.OK)
          {
             check.performTask(monitor);
          }

          return validateStatus;
       }
    }

And the above ValidateJob is started by an Eclipse Menu option defined below:

    package com.ngc.sna.cx.extensions.contributors;

    import static org.eclipse.core.resources.ResourcesPlugin.getWorkspace;
    import static org.eclipse.swt.SWT.CASCADE;
    import static org.eclipse.swt.SWT.PUSH;

    import java.util.Arrays;
    import java.util.List;

    import org.eclipse.core.resources.IProject;
    import org.eclipse.jface.dialogs.IDialogConstants;
    import org.eclipse.jface.dialogs.MessageDialog;
    import org.eclipse.swt.events.SelectionAdapter;
    import org.eclipse.swt.events.SelectionEvent;
    import org.eclipse.swt.widgets.Menu;
    import org.eclipse.swt.widgets.MenuItem;

    import com.ngc.sna.common.dialogs.RestrictedMessageDialog;
    import com.ngc.sna.common.images.Images;
    import com.ngc.sna.menu.content.SNAToolsMenuContributor;
    import com.ngc.sna.scripts.utils.ConsistencyChecker;

    public class ModelingUtilitiesContributor extends SNAToolsMenuContributor
    {
       private MenuItem menuItem;
       private Menu menu;
       private MenuItem generateIDL;
       private MenuItem generateDescriptors;
       private MenuItem validateModels;
       private MenuItem checkICM;

       /*
        * (non-Javadoc)
        * @see com.ngc.sna.menu.content.SNAToolsMenuContributor#dispose()
        */
       @Override
       public void dispose()
       {

          if (validateModels != null)
          {
             validateModels.dispose();
             validateModels = null;
          }

          if (menu != null)
          {
             menu.dispose();
             menu = null;
          }

          if (menuItem != null)
          {
             menuItem.dispose();
             menuItem = null;
          }

       }

       /*
        * (non-Javadoc)
        * @see com.ngc.sna.menu.content.SNAToolsMenuContributor#fill(org.eclipse.swt.widgets.Menu, int)
        */
       @Override
       public void fill(Menu parent, int index)
       {
          menuItem = new MenuItem(parent, CASCADE, index);
          menuItem.setText(getName());

          menu = new Menu(menuItem);
          menuItem.setMenu(menu);

          validateModels = new MenuItem(menu, PUSH);
          validateModels.setText("Validate Models");
          validateModels.addSelectionListener(new SelectionAdapter()
          {
             /*
              * (non-Javadoc)
              * @see org.eclipse.swt.events.SelectionAdapter#widgetSelected(org.eclipse.swt.events.SelectionEvent)
              */
             @Override
             public void widgetSelected(SelectionEvent e)
             {
                List<IProject> allProjects = Arrays.asList(getWorkspace().getRoot().getProjects());

                if (allProjects.size() != 0)
                {
                   ValidateJob validJob = new ValidateJob(allProjects);
                   validJob.schedule();
                }
                else
                {
                   MessageDialog dialog = new RestrictedMessageDialog(null, "SNA Info Dialog", Images.getSNAIcon(),
                         "There are no models to validate Models for.", MessageDialog.INFORMATION,
                         new String[] { IDialogConstants.OK_LABEL }, 0);
                   dialog.open();
                }
             }
          });

       }

       /*
        * (non-Javadoc)
        * @see com.ngc.sna.menu.content.SNAToolsMenuContributor#getName()
        */
       @Override
       public String getName()
       {
          return "&Modeling Utilities";
       }

       /*
        * (non-Javadoc)
        * @see com.ngc.sna.menu.content.SNAToolsMenuContributor#setVisible(boolean)
        */
       @Override
       public void setVisible(boolean visible)
       {
       }

    }

**Comment by ysroh** [comment]
Thanks. The error log is very helpful. Looks like there is a problem manipulating the URI to get the Papyrus di file.
Does the checker go through all the UML models in the workspace? or does it bring up the dialog so that user chooses the model to validate? 
Is there a chance that GenerateUtils.convertToURI(model) returns null URI?

**Comment by ysroh** [comment]
I will add some validation on URI provided and log the results into error log.

**Comment by ysroh** [comment]
In the meantime, is it possible to show me the GenerationUtils.convertToUri(model) code? I am trying to see if it returns platform resource uri or file uri. Thanks

**Comment by J17359** [comment]
> Does the checker go through all the UML models in the workspace? or does it bring up the dialog so that user chooses the model to validate?

Once the user selects the "validate models" menu option, they are prompted with a list of all UML files in the workspace. Whichever ones they check from that selection are those that get looped over in the ValidateChecker class.

> Is there a chance that GenerateUtils.convertToURI(model) returns null URI?

I'll have to test this and let you know

**Comment by J17359** [comment]
> 
> 
> In the meantime, is it possible to show me the GenerationUtils.convertToUri(model) code? I am trying to see if it returns platform resource uri or file uri.

    public class GenerateUtils
    {
       /**
        * This method converts the given IFile to a URI
        * 
        * @param model a model in the workspace
        * @return a URI to the given model
        * @throws CoreException if no URI could be determined
        */
       public static URI convertToURI(IFile model) throws CoreException
       {
          // Get the filesystem location of the model
          java.net.URI location = model.getLocationURI();

          // Report error if location could not be determined
          if (location == null)
          {
             throw new CoreException(new Status(ERROR, PLUGIN_ID, "No URI could be determined for " + model));
          }

          // Create a URI from the location
          return URI.createURI(location.toString());
       }

       /**
        * Finds all *.uml files in a given project and returns them in a set sorted by project relative path
        * 
        * @param sourceProject the project to search
        * @param monitor progress monitor (only used to check for cancellation)
        * @return a sorted set of *.uml files
        * @throws CoreException if the operation is canceled
        */
       public static SortedSet<IFile> getAllModelsIn(IProject sourceProject, final IProgressMonitor monitor)
             throws CoreException
       {
          // Keep the return collection sorted by project relative path
          final SortedSet<IFile> models = new TreeSet<>(new Comparator<IFile>()
          {
             /*
              * (non-Javadoc)
              * @see java.util.Comparator#compare(java.lang.Object, java.lang.Object)
              */
             @Override
             public int compare(IFile o1, IFile o2)
             {
                String p1 = o1.getProjectRelativePath().toOSString();
                String p2 = o2.getProjectRelativePath().toOSString();
                return p1.compareTo(p2);
             }
          });

          sourceProject.accept(new IResourceProxyVisitor()
          {
             /**
              * @see IResourceProxyVisitor#visit(IResourceProxy)
              */
             @Override
             public boolean visit(IResourceProxy proxy) throws CoreException
             {
                // Stop if canceled
                if (monitor.isCanceled())
                {
                   throw new CoreException(CANCEL_STATUS);
                }

                // Check for *.uml files
                if (proxy.getType() != FILE || !proxy.getName().endsWith(".uml"))
                {
                   return true;
                }

                // Don't add the .uml file if it is read only
                if (proxy.requestResource().getResourceAttributes().isReadOnly())
                {
                   return true;
                }

                // Store *.uml files
                models.add((IFile) proxy.requestResource());

                return true;
             }
          }, NONE);

          return models;
       }
    }

**Comment by J17359** [comment]
FYI. I tested calling the following two scenarios:
* Old way - `CodeGenUtil.validateModel(URI.createURI(<IFile>.getLocationURI().toString)` - always returns OK status regardless of invalid/valid model passed in 
  * `createURI` returns "file:/home/user/.../BasicPubSub.uml"
* Your way - `CodeGenUtil.validateModel(URI.createPlatformResourceURI(<IFile>.getLocationURI().toString, true)` - always returns ERROR status regardless of invalid/valid model passed in
  * `createPlatformResourceURI` returns "platform:/resource/file:/home/user/.../BasicPubSub.uml"

**Comment by ysroh** [comment]
I see. The location URI is a file URI. My assumption was that the platform resource URI was provided for the validation model. I will put a fix in to handle both types of URI. Thanks.

**Comment by ysroh** [comment]
Your way - CodeGenUtil.validateModel(URI.createPlatformResourceURI(<IFile>.getLocationURI().toString, true) - always returns ERROR status regardless of invalid/valid model passed in
createPlatformResourceURI returns "platform:/resource/file:/home/user/.../BasicPubSub.uml"

It should be <IFile>.getFullPath() instead of getLocationURI.
So the following is the correct way.
CodeGenUtil.validateModel(URI.createPlatformResourceURI(<IFile>.getFullPath().toString, true)

**Comment by J17359** [comment]
> It should be .getFullPath() instead of getLocationURI.
> So the following is the correct way.
> CodeGenUtil.validateModel(URI.createPlatformResourceURI(model.getFullPath().toString, true)

That worked! Everything works as expected now. Multiple models validate successfully whether already opened or not.

**Comment by J17359** [comment]
Would you mind adding another line to your model validation printout that goes to the Console? Right now it's:

    Validated Model : platform/r...
    Validation - 0 error(s), 0 warning(s)

If there are errors/warnings, they show in the "Model Validation" view, not the console view so maybe it could be something like:

    Validated Model : platform/r...
    Validation - 0 error(s), 0 warning(s)
    See "Model Validation" view for error(s)/warning(s), if any

**Comment by ysroh** [comment]
Great!!!!. So the problem was that the file URI was used instead of Platform uri. It didn't really matter in RSA since no UI was involved and the RSA resource set handles both types of URI.

Yes. I will add a line to the console.

**Comment by ysroh** [comment]
Do you still want me to handle both types of URI? or are you ok with the current solution + adding the extra line?

**Comment by J17359** [comment]
> 
> 
> Do you still want me to handle both types of URI? or are you ok with the current solution + adding the extra line?

If it wouldn't be too much trouble, handling both types of URIs would be nice because we wouldn't have to touch our code, but if it's difficult, feel free to leave it as is and I'll make the change on our end. Just let me know! Thanks again!

**Comment by ysroh** [comment]
No problem. I will put a fix in. Thanks

**Comment by ysroh** [comment]
This should be fixed now. I only added the extra line when there is at least one warning or error.

**Comment by J17359** [comment]
Looks great @ysroh ! Thanks for helping us with this. 

I ran your code with our CodeGenUtils.validateModel() invocation and verified models successfully passed when valid and were caught when invalid and that helpful information was displayed to the user in both cases.
